// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcywKMe2ffSraSJNNmKU7W-bewJhT62kQ',
    appId: '1:734257869021:web:d0533cdd395beaf707eb34',
    messagingSenderId: '734257869021',
    projectId: 'uaintervention-c4c2f',
    authDomain: 'uaintervention-c4c2f.firebaseapp.com',
    storageBucket: 'uaintervention-c4c2f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF0U8NLjilTotw5mXiu-qHc1XuxL-hUK8',
    appId: '1:734257869021:android:f5431c851a1b5f5007eb34',
    messagingSenderId: '734257869021',
    projectId: 'uaintervention-c4c2f',
    storageBucket: 'uaintervention-c4c2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0dnEMnso3f9mokp9W7gvpaZ4v6hKgNoA',
    appId: '1:734257869021:ios:c3690138d88bdcdb07eb34',
    messagingSenderId: '734257869021',
    projectId: 'uaintervention-c4c2f',
    storageBucket: 'uaintervention-c4c2f.firebasestorage.app',
    iosBundleId: 'com.example.uaInterventionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0dnEMnso3f9mokp9W7gvpaZ4v6hKgNoA',
    appId: '1:734257869021:ios:c3690138d88bdcdb07eb34',
    messagingSenderId: '734257869021',
    projectId: 'uaintervention-c4c2f',
    storageBucket: 'uaintervention-c4c2f.firebasestorage.app',
    iosBundleId: 'com.example.uaInterventionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcywKMe2ffSraSJNNmKU7W-bewJhT62kQ',
    appId: '1:734257869021:web:2d46cd82b516cdb707eb34',
    messagingSenderId: '734257869021',
    projectId: 'uaintervention-c4c2f',
    authDomain: 'uaintervention-c4c2f.firebaseapp.com',
    storageBucket: 'uaintervention-c4c2f.firebasestorage.app',
  );
}
