# Uncomment the next line to define a global platform for your project
platform :ios, '15.5'

use_frameworks!
use_modular_headers!

# CocoaPods analytics send network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Find the Flutter SDK path automatically
flutter_root = `flutter --version --machine`.match(/"flutterRoot":\s*"([^"]+)"/)[1]

load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end